import Vue from 'vue'
import Vuex from 'vuex'

Vue.use Vuex

export default new Vuex.Store
	state:
		user:
			username: 'lytedev'
			email: 'daniel@lytedev.io'
			fullname: 'Daniel Flanagan'
		playlists: 'p_hash_id_1?': songs: [
			's_hash_id_1'
			's_hash_id_2'
		]
		songs:
			's_hash_id_1':
				name: 'Song Title'
				maps: 'default_map': [ 'generated by client?' ]
			's_hash_id_2':
				name: 'Song Title'
				maps:
					'default_map': [ 'generated by client?' ]
					'custom_map': [
						'title'
						'v1'
						'v2'
					]
				verses:
					'title': 'Song Title'
					'v1': 'This is\nVerse 1'
		loading: false
	mutations: loading: (state) ->
		state.loading = true
		return
