import Vue from 'vue'
import Vuex from 'vuex'

Vue.use Vuex

# TODO: store whether or not the user last had the menu open

export default new Vuex.Store
	state:
		user: {}
			# username: 'lytedev'
			# email: 'daniel@lytedev.io'
			# fullname: 'Daniel Flanagan'
		playlists:
			'p_hash_id_1?':
				name: "Defull"
				songs: [
					's_hash_id_1'
					's_hash_id_2'
				]
		songs:
			's_hash_id_1':
				name: 'Song 1 Title'
				maps: 'default_map': [ 'generated by client?' ]
			's_hash_id_2':
				name: 'Song 2 Title'
				maps:
					'default_map': [ 'generated by client?' ]
					'custom_map': [
						'title'
						'v1'
						'v2'
					]
				verses:
					'title': 'Song Title'
					'v1': 'This is\nVerse 1'
		loading: false
	getters:
		currentPlaylist: (state) ->
			console.log "currentPlaylist()", state
			return state.playlists[Object.keys(state.playlists)[0]]
		currentSongs: (state, getters) ->
			console.log "currentSongs()", state, getters
			cpl = getters.currentPlaylist
			if not cpl? then return
			songs = []
			songs.push(state.songs[s]) for s in cpl.songs
			return songs
	mutations: loading: (state) ->
		state.loading = true
		return
